"""empty message

Revision ID: dcff5f57b3b6
Revises: 45f5c62a8b98
Create Date: 2023-10-05 18:20:22.249295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import app


# revision identifiers, used by Alembic.
revision = 'dcff5f57b3b6'
down_revision = '45f5c62a8b98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('version', sa.Integer(), nullable=False, server_default="1"))
    op.drop_constraint('unique_topic_model', 'course', type_='unique')
    op.create_unique_constraint('unique_topic_model_version', 'course', ['topic', 'model', 'version'])
    op.add_column('prompt', sa.Column('version', sa.Integer(), nullable=False, server_default="1"))
    op.drop_constraint('unique_hash_model', 'prompt', type_='unique')
    op.create_unique_constraint('unique_hash_model_version', 'prompt', ['hash', 'model', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_hash_model_version', 'prompt', type_='unique')
    op.create_unique_constraint('unique_hash_model', 'prompt', ['hash', 'model'])
    op.drop_column('prompt', 'version')
    op.drop_constraint('unique_topic_model_version', 'course', type_='unique')
    op.create_unique_constraint('unique_topic_model', 'course', ['topic', 'model'])
    op.drop_column('course', 'version')
    # ### end Alembic commands ###
