"""empty message

Revision ID: a245397ecff0
Revises: dcff5f57b3b6
Create Date: 2023-10-18 13:25:11.463550

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import app


# revision identifiers, used by Alembic.
revision = 'a245397ecff0'
down_revision = 'dcff5f57b3b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('potential_outline_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'potential_outline_items')
    # ### end Alembic commands ###
